import { library } from '@fortawesome/fontawesome-svg-core'

//粗体
import { 
    faMagnifyingGlass, 
    faArrowsRotate,
    faSave,
    faFileInvoice,
    faFolderPlus,
    faSitemap,
    faOutdent,
    faIndent,
    faHome,
    faAngleDown,
    faAddressCard,
    faKey,
    faArrowsAlt,
    faUser,
    faUserPlus,
    faUsers,
    faUserTie,
    faRefresh,
    faSearch,
    faReply,
    faPlus,
    faDownload,
    faAngleDoubleDown,
    faAngleDoubleUp,
    faEye,
    faEyeSlash,
    faBars,
    faBarcode,
    faInfoCircle,
    faPlusCircle,
    faTrashAlt,
    faPencilSquare,
    faFileExcel,
    faAngleRight,
    faFlask,
    faPaperPlane,
    faArrowCircleDown,
    faAlignLeft,
    faEdit,
    faCog,
    faCogs,
    faBan,
    faUndo,
    faUpload,
    faRetweet,
    faExclamationCircle,
    faShield,
    faTasks,
    faLaptopCode,
    faGlobe,
    faListAlt,
    faBoxes,
    faDollyFlatbed,
    faCartPlus,
    faBarChart,
    faBinoculars,
    faSackDollar,
    faUserShield,
    faWrench,
    faDesktop,
    faList,
    faQrcode,
    faPowerOff,
    faPrint,
    faFilePdf,
    faTimesCircle,
    faCloudDownload,
} from '@fortawesome/free-solid-svg-icons'
library.add(
    faMagnifyingGlass, 
    faArrowsRotate,
    faSave,
    faFileInvoice,
    faFolderPlus,
    faSitemap,
    faOutdent,
    faIndent,
    faHome,
    faAngleDown,
    faAddressCard,
    faKey,
    faArrowsAlt,
    faUser,
    faUserPlus,
    faUsers,
    faUserTie,
    faRefresh,
    faSearch,
    faReply,
    faPlus,
    faDownload,
    faAngleDoubleDown,
    faAngleDoubleUp,
    faEye,
    faEyeSlash,
    faBars,
    faBarcode,
    faInfoCircle,
    faPlusCircle,
    faTrashAlt,
    faPencilSquare,
    faFileExcel,
    faAngleRight,
    faFlask,
    faPaperPlane,
    faArrowCircleDown,
    faAlignLeft,
    faEdit,
    faCog,
    faCogs,
    faBan,
    faUndo,
    faUpload,
    faRetweet,
    faExclamationCircle,
    faShield,
    faTasks,
    faLaptopCode,
    faGlobe,
    faListAlt,
    faBoxes,
    faDollyFlatbed,
    faCartPlus,
    faBarChart,
    faBinoculars,
    faSackDollar,
    faUserShield,
    faWrench,
    faDesktop,
    faList,
    faQrcode,
    faPowerOff,
    faPrint,
    faFilePdf,
    faTimesCircle,
    faCloudDownload)

//常规
import { 
    faSave as farSave,
    faImage as farImage,
    faEdit as farEdit,
    faTrashAlt as farTrashAlt,
    faBuilding as farBuilding,
    faHandshake as farHandshake,
    faCheckSquare as farCheckSquare,
    faEnvelope as farEnvelope,
    faPenToSquare as farPenToSquare,
    faPlayCircle as farPlayCircle,
    faFileExcel  as farFileExcel
} from '@fortawesome/free-regular-svg-icons'
library.add(farSave,
    farImage,
    farEdit,
    farTrashAlt,
    farBuilding,
    farHandshake,
    farCheckSquare,
    farEnvelope,
    farPenToSquare,
    farPlayCircle,
    farFileExcel)
